---
title: "Mushrooms"
author: "Olga Shiligin"
date: "30 August 2018"
output: html_document
---

1. Importing data and creating data frame.
----------------------------------------------

```{r}
mashrooms<- read.csv("https://raw.githubusercontent.com/olgashiligin/mashrooms/6f7e34e41029bdf8d2419d5d8e67e319a211853a/raw_data",header = FALSE, stringsAsFactors=FALSE)
df<-data.frame(mashrooms)
head(df)
```

2. Creating data frame with a subset of the columns in the dataset.
----------------------------------------------------------------------
```{r}
mushroom_subset <- subset(df, select = c(1,2,3,6,19))
head(mushroom_subset)
```

3.Adding column names.
----------------------------
```{r}
colnames(mushroom_subset)<-c("type","cap_shape","cap_surface","odor","ring_number")
head(mushroom_subset)
```

4. Replacing abbreviations
---------------------------------
```{r}
mushroom_subset$type[mushroom_subset$type == "p"] <- "poisonous"
mushroom_subset$type[mushroom_subset$type == "e"] <- "edible"
mushroom_subset$cap_shape[mushroom_subset$cap_shape == "b"] <- "bell"
mushroom_subset$cap_shape[mushroom_subset$cap_shape == "c"] <- "conical"
mushroom_subset$cap_shape[mushroom_subset$cap_shape == "x"] <- "convex"
mushroom_subset$cap_shape[mushroom_subset$cap_shape == "f"] <- "flat"
mushroom_subset$cap_shape[mushroom_subset$cap_shape == "k"] <- "knobbed"
mushroom_subset$cap_shape[mushroom_subset$cap_shape == "s"] <- "sunken"
mushroom_subset$cap_surface[mushroom_subset$cap_surface == "f"] <- "fibrous"
mushroom_subset$cap_surface[mushroom_subset$cap_surface == "g"] <- "grooves"
mushroom_subset$cap_surface[mushroom_subset$cap_surface == "y"] <- "scaly"
mushroom_subset$cap_surface[mushroom_subset$cap_surface == "s"] <- "smooth"
mushroom_subset$odor[mushroom_subset$odor == "a"] <- "almond"
mushroom_subset$odor[mushroom_subset$odor == "l"] <- "anise"
mushroom_subset$odor[mushroom_subset$odor == "c"] <- "creosote"
mushroom_subset$odor[mushroom_subset$odor == "y"] <- "fishy"
mushroom_subset$odor[mushroom_subset$odor == "f"] <- "foul"
mushroom_subset$odor[mushroom_subset$odor == "m"] <- "musty"
mushroom_subset$odor[mushroom_subset$odor == "n"] <- "none"
mushroom_subset$odor[mushroom_subset$odor == "p"] <- "pungent"
mushroom_subset$odor[mushroom_subset$odor == "s"] <- "spicy"
mushroom_subset$ring_number[mushroom_subset$ring_number == "n"] <- "none"
mushroom_subset$ring_number[mushroom_subset$ring_number == "o"] <- "one"
mushroom_subset$ring_number[mushroom_subset$ring_number == "t"] <- "two"

```

5. Result
----------
```{r}
head(mushroom_subset)
```

